### ISSUE TITLE
Project Example Broken!? No Data Points visible

### ISSUE THREAD

**Issue by johnkelton** [perrygeo/pi_sensor_realtime#3]
I followed the following tutorial word by word:
http://www.perrygeo.com/raspberry-pi-real-time-sensor-plots-with-websocketd.html

But my plot is empty i.e. no data point. Even though my log.txt file has data points. My python script and WebSocketd is working as I can see the index.html turn green and also --devconsole works. You can download the project from here and try it:

https://github.com/perrygeo/pi_sensor_realtime

**Comment by dell-helpdesk** [comment]
I'm having a similar issue, was this ever resolved?

**Comment by perrygeo** [comment]
@johnkelton @dell-helpdesk Let me put this as gently as possible: If you want a good answer, you need to ask a good question. Saying "It doesn't work!?" gives me exactly zero information with which to help you.

I took the time to learn these technologies, to work through the specific problems using the scientific method, to find resources online to get myself unstuck. I suggest you do the same.
